name: SimpleEcom

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
    pull_request:
        branches:
            - master
          
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                dotnet-version: [ '9.0.x' ]

        env:
            MODE: "dev"

        steps: 
        - uses: actions/checkout@v4
        - name: Setup dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '9.0.x'
        - name: Install dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Test with the dotnet CLI
          run: dotnet test --no-build
