name: SimpleEcom

on:
    pull_request:
        branches:
            - master
          
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                dotnet-version: [ '9.0.x' ]

        env:
            MODE: "dev"

        steps: 
        - uses: actions/checkout@v4
        - name: Setup dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '9.0.x'
        - name: Install dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --no-restore
        - name: Test with the dotnet CLI
          run: dotnet test --no-build
